/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CloberMarketFlashCallbackReceiver,
  CloberMarketFlashCallbackReceiverInterface,
} from "../../../contracts/interfaces/CloberMarketFlashCallbackReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "quoteToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "baseToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "quoteAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "baseAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "quoteFeeAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "baseFeeAmount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "cloberMarketFlashCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class CloberMarketFlashCallbackReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): CloberMarketFlashCallbackReceiverInterface {
    return new utils.Interface(
      _abi
    ) as CloberMarketFlashCallbackReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CloberMarketFlashCallbackReceiver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CloberMarketFlashCallbackReceiver;
  }
}
