/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CloberPriceBookDeployer,
  CloberPriceBookDeployerInterface,
} from "../../../contracts/interfaces/CloberPriceBookDeployer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint128",
        name: "a",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "d",
        type: "uint128",
      },
    ],
    name: "computeArithmeticPriceBookAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "a",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "r",
        type: "uint128",
      },
    ],
    name: "computeGeometricPriceBookAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "a",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "d",
        type: "uint128",
      },
    ],
    name: "deployArithmeticPriceBook",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "a",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "r",
        type: "uint128",
      },
    ],
    name: "deployGeometricPriceBook",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class CloberPriceBookDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): CloberPriceBookDeployerInterface {
    return new utils.Interface(_abi) as CloberPriceBookDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CloberPriceBookDeployer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CloberPriceBookDeployer;
  }
}
