/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface CloberMarketFlashCallbackReceiverInterface
  extends utils.Interface {
  functions: {
    "cloberMarketFlashCallback(address,address,uint256,uint256,uint256,uint256,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "cloberMarketFlashCallback"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cloberMarketFlashCallback",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "cloberMarketFlashCallback",
    data: BytesLike
  ): Result;

  events: {};
}

export interface CloberMarketFlashCallbackReceiver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CloberMarketFlashCallbackReceiverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cloberMarketFlashCallback(
      quoteToken: string,
      baseToken: string,
      quoteAmount: BigNumberish,
      baseAmount: BigNumberish,
      quoteFeeAmount: BigNumberish,
      baseFeeAmount: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  cloberMarketFlashCallback(
    quoteToken: string,
    baseToken: string,
    quoteAmount: BigNumberish,
    baseAmount: BigNumberish,
    quoteFeeAmount: BigNumberish,
    baseFeeAmount: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    cloberMarketFlashCallback(
      quoteToken: string,
      baseToken: string,
      quoteAmount: BigNumberish,
      baseAmount: BigNumberish,
      quoteFeeAmount: BigNumberish,
      baseFeeAmount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    cloberMarketFlashCallback(
      quoteToken: string,
      baseToken: string,
      quoteAmount: BigNumberish,
      baseAmount: BigNumberish,
      quoteFeeAmount: BigNumberish,
      baseFeeAmount: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cloberMarketFlashCallback(
      quoteToken: string,
      baseToken: string,
      quoteAmount: BigNumberish,
      baseAmount: BigNumberish,
      quoteFeeAmount: BigNumberish,
      baseFeeAmount: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
