/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface GasReporterInterface extends utils.Interface {
  functions: {
    "EHDT_CancelRemainingAskOrder(uint256)": FunctionFragment;
    "EHDT_CancelRemainingBidOrder(uint256)": FunctionFragment;
    "EHDT_FullyCancelAsk(uint256)": FunctionFragment;
    "EHDT_FullyCancelBid(uint256)": FunctionFragment;
    "EHDT_FullyClaimAsk(bool,uint16,uint256)": FunctionFragment;
    "EHDT_FullyClaimBid(bool,uint16,uint256)": FunctionFragment;
    "EHDT_FullyMarketAsk(address,uint256)": FunctionFragment;
    "EHDT_FullyMarketBid(address,uint64)": FunctionFragment;
    "EHDT_LimitAsk(address,uint16,uint256)": FunctionFragment;
    "EHDT_LimitBid(address,uint16,uint64)": FunctionFragment;
    "EHDT_PartiallyCancelAsk(uint256)": FunctionFragment;
    "EHDT_PartiallyCancelBid(uint256)": FunctionFragment;
    "EHDT_PartiallyClaimAsk(bool,uint16,uint256)": FunctionFragment;
    "EHDT_PartiallyClaimBid(bool,uint16,uint256)": FunctionFragment;
    "EHDT_PartiallyMarketAsk(address,uint256)": FunctionFragment;
    "EHDT_PartiallyMarketBid(address,uint64)": FunctionFragment;
    "EHET_CancelRemainingAskOrder(uint256)": FunctionFragment;
    "EHET_CancelRemainingBidOrder(uint256)": FunctionFragment;
    "EHET_FullyCancelAsk(uint256)": FunctionFragment;
    "EHET_FullyCancelBid(uint256)": FunctionFragment;
    "EHET_FullyClaimAsk(bool,uint16,uint256)": FunctionFragment;
    "EHET_FullyClaimBid(bool,uint16,uint256)": FunctionFragment;
    "EHET_FullyMarketAsk(address,uint256)": FunctionFragment;
    "EHET_FullyMarketBid(address,uint64)": FunctionFragment;
    "EHET_LimitAsk(address,uint16,uint256)": FunctionFragment;
    "EHET_LimitBid(address,uint16,uint64)": FunctionFragment;
    "EHET_PartiallyCancelAsk(uint256)": FunctionFragment;
    "EHET_PartiallyCancelBid(uint256)": FunctionFragment;
    "EHET_PartiallyClaimAsk(bool,uint16,uint256)": FunctionFragment;
    "EHET_PartiallyClaimBid(bool,uint16,uint256)": FunctionFragment;
    "EHET_PartiallyMarketAsk(address,uint256)": FunctionFragment;
    "EHET_PartiallyMarketBid(address,uint64)": FunctionFragment;
    "FHET_CancelRemainingAskOrder(uint256)": FunctionFragment;
    "FHET_CancelRemainingBidOrder(uint256)": FunctionFragment;
    "FHET_FullyCancelAsk(uint256)": FunctionFragment;
    "FHET_FullyCancelBid(uint256)": FunctionFragment;
    "FHET_FullyClaimAsk(bool,uint16,uint256)": FunctionFragment;
    "FHET_FullyClaimBid(bool,uint16,uint256)": FunctionFragment;
    "FHET_FullyMarketAsk(address,uint256)": FunctionFragment;
    "FHET_FullyMarketBid(address,uint64)": FunctionFragment;
    "FHET_LimitAsk(address,uint16,uint256)": FunctionFragment;
    "FHET_LimitBid(address,uint16,uint64)": FunctionFragment;
    "FHET_PartiallyCancelAsk(uint256)": FunctionFragment;
    "FHET_PartiallyCancelBid(uint256)": FunctionFragment;
    "FHET_PartiallyClaimAsk(bool,uint16,uint256)": FunctionFragment;
    "FHET_PartiallyClaimBid(bool,uint16,uint256)": FunctionFragment;
    "FHET_PartiallyMarketAsk(address,uint256)": FunctionFragment;
    "FHET_PartiallyMarketBid(address,uint64)": FunctionFragment;
    "FHFT_CancelRemainingAskOrder(uint256)": FunctionFragment;
    "FHFT_CancelRemainingBidOrder(uint256)": FunctionFragment;
    "FHFT_FullyCancelAsk(uint256)": FunctionFragment;
    "FHFT_FullyCancelBid(uint256)": FunctionFragment;
    "FHFT_FullyClaimAsk(bool,uint16,uint256)": FunctionFragment;
    "FHFT_FullyClaimBid(bool,uint16,uint256)": FunctionFragment;
    "FHFT_FullyMarketAsk(address,uint256)": FunctionFragment;
    "FHFT_FullyMarketBid(address,uint64)": FunctionFragment;
    "FHFT_LimitAsk(address,uint16,uint256)": FunctionFragment;
    "FHFT_LimitBid(address,uint16,uint64)": FunctionFragment;
    "FHFT_PartiallyCancelAsk(uint256)": FunctionFragment;
    "FHFT_PartiallyCancelBid(uint256)": FunctionFragment;
    "FHFT_PartiallyClaimAsk(bool,uint16,uint256)": FunctionFragment;
    "FHFT_PartiallyClaimBid(bool,uint16,uint256)": FunctionFragment;
    "FHFT_PartiallyMarketAsk(address,uint256)": FunctionFragment;
    "FHFT_PartiallyMarketBid(address,uint64)": FunctionFragment;
    "cancelOrder(uint256)": FunctionFragment;
    "claimOrder(bool,uint16,uint256)": FunctionFragment;
    "limitAskOrder(address,uint16,uint256,bool)": FunctionFragment;
    "limitBidOrder(address,uint16,uint64,bool)": FunctionFragment;
    "marketAskOrder(address,uint256)": FunctionFragment;
    "marketBidOrder(address,uint64)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "EHDT_CancelRemainingAskOrder"
      | "EHDT_CancelRemainingBidOrder"
      | "EHDT_FullyCancelAsk"
      | "EHDT_FullyCancelBid"
      | "EHDT_FullyClaimAsk"
      | "EHDT_FullyClaimBid"
      | "EHDT_FullyMarketAsk"
      | "EHDT_FullyMarketBid"
      | "EHDT_LimitAsk"
      | "EHDT_LimitBid"
      | "EHDT_PartiallyCancelAsk"
      | "EHDT_PartiallyCancelBid"
      | "EHDT_PartiallyClaimAsk"
      | "EHDT_PartiallyClaimBid"
      | "EHDT_PartiallyMarketAsk"
      | "EHDT_PartiallyMarketBid"
      | "EHET_CancelRemainingAskOrder"
      | "EHET_CancelRemainingBidOrder"
      | "EHET_FullyCancelAsk"
      | "EHET_FullyCancelBid"
      | "EHET_FullyClaimAsk"
      | "EHET_FullyClaimBid"
      | "EHET_FullyMarketAsk"
      | "EHET_FullyMarketBid"
      | "EHET_LimitAsk"
      | "EHET_LimitBid"
      | "EHET_PartiallyCancelAsk"
      | "EHET_PartiallyCancelBid"
      | "EHET_PartiallyClaimAsk"
      | "EHET_PartiallyClaimBid"
      | "EHET_PartiallyMarketAsk"
      | "EHET_PartiallyMarketBid"
      | "FHET_CancelRemainingAskOrder"
      | "FHET_CancelRemainingBidOrder"
      | "FHET_FullyCancelAsk"
      | "FHET_FullyCancelBid"
      | "FHET_FullyClaimAsk"
      | "FHET_FullyClaimBid"
      | "FHET_FullyMarketAsk"
      | "FHET_FullyMarketBid"
      | "FHET_LimitAsk"
      | "FHET_LimitBid"
      | "FHET_PartiallyCancelAsk"
      | "FHET_PartiallyCancelBid"
      | "FHET_PartiallyClaimAsk"
      | "FHET_PartiallyClaimBid"
      | "FHET_PartiallyMarketAsk"
      | "FHET_PartiallyMarketBid"
      | "FHFT_CancelRemainingAskOrder"
      | "FHFT_CancelRemainingBidOrder"
      | "FHFT_FullyCancelAsk"
      | "FHFT_FullyCancelBid"
      | "FHFT_FullyClaimAsk"
      | "FHFT_FullyClaimBid"
      | "FHFT_FullyMarketAsk"
      | "FHFT_FullyMarketBid"
      | "FHFT_LimitAsk"
      | "FHFT_LimitBid"
      | "FHFT_PartiallyCancelAsk"
      | "FHFT_PartiallyCancelBid"
      | "FHFT_PartiallyClaimAsk"
      | "FHFT_PartiallyClaimBid"
      | "FHFT_PartiallyMarketAsk"
      | "FHFT_PartiallyMarketBid"
      | "cancelOrder"
      | "claimOrder"
      | "limitAskOrder"
      | "limitBidOrder"
      | "marketAskOrder"
      | "marketBidOrder"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "EHDT_CancelRemainingAskOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_CancelRemainingBidOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_FullyCancelAsk",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_FullyCancelBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_FullyClaimAsk",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_FullyClaimBid",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_FullyMarketAsk",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_FullyMarketBid",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_LimitAsk",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_LimitBid",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_PartiallyCancelAsk",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_PartiallyCancelBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_PartiallyClaimAsk",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_PartiallyClaimBid",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_PartiallyMarketAsk",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHDT_PartiallyMarketBid",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_CancelRemainingAskOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_CancelRemainingBidOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_FullyCancelAsk",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_FullyCancelBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_FullyClaimAsk",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_FullyClaimBid",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_FullyMarketAsk",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_FullyMarketBid",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_LimitAsk",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_LimitBid",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_PartiallyCancelAsk",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_PartiallyCancelBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_PartiallyClaimAsk",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_PartiallyClaimBid",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_PartiallyMarketAsk",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "EHET_PartiallyMarketBid",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_CancelRemainingAskOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_CancelRemainingBidOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_FullyCancelAsk",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_FullyCancelBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_FullyClaimAsk",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_FullyClaimBid",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_FullyMarketAsk",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_FullyMarketBid",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_LimitAsk",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_LimitBid",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_PartiallyCancelAsk",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_PartiallyCancelBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_PartiallyClaimAsk",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_PartiallyClaimBid",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_PartiallyMarketAsk",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHET_PartiallyMarketBid",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_CancelRemainingAskOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_CancelRemainingBidOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_FullyCancelAsk",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_FullyCancelBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_FullyClaimAsk",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_FullyClaimBid",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_FullyMarketAsk",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_FullyMarketBid",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_LimitAsk",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_LimitBid",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_PartiallyCancelAsk",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_PartiallyCancelBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_PartiallyClaimAsk",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_PartiallyClaimBid",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_PartiallyMarketAsk",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FHFT_PartiallyMarketBid",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimOrder",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "limitAskOrder",
    values: [string, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "limitBidOrder",
    values: [string, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "marketAskOrder",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketBidOrder",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "EHDT_CancelRemainingAskOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_CancelRemainingBidOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_FullyCancelAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_FullyCancelBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_FullyClaimAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_FullyClaimBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_FullyMarketAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_FullyMarketBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_LimitAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_LimitBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_PartiallyCancelAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_PartiallyCancelBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_PartiallyClaimAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_PartiallyClaimBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_PartiallyMarketAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHDT_PartiallyMarketBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_CancelRemainingAskOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_CancelRemainingBidOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_FullyCancelAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_FullyCancelBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_FullyClaimAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_FullyClaimBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_FullyMarketAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_FullyMarketBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_LimitAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_LimitBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_PartiallyCancelAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_PartiallyCancelBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_PartiallyClaimAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_PartiallyClaimBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_PartiallyMarketAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EHET_PartiallyMarketBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_CancelRemainingAskOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_CancelRemainingBidOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_FullyCancelAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_FullyCancelBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_FullyClaimAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_FullyClaimBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_FullyMarketAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_FullyMarketBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_LimitAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_LimitBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_PartiallyCancelAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_PartiallyCancelBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_PartiallyClaimAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_PartiallyClaimBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_PartiallyMarketAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHET_PartiallyMarketBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_CancelRemainingAskOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_CancelRemainingBidOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_FullyCancelAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_FullyCancelBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_FullyClaimAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_FullyClaimBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_FullyMarketAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_FullyMarketBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_LimitAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_LimitBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_PartiallyCancelAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_PartiallyCancelBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_PartiallyClaimAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_PartiallyClaimBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_PartiallyMarketAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FHFT_PartiallyMarketBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "limitAskOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "limitBidOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketAskOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketBidOrder",
    data: BytesLike
  ): Result;

  events: {};
}

export interface GasReporter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GasReporterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    EHDT_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHDT_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    EHET_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHET_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    FHFT_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    cancelOrder(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    claimOrder(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    limitAskOrder(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      postOnly: boolean,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    limitBidOrder(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      postOnly: boolean,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    marketAskOrder(
      user: string,
      baseAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    marketBidOrder(
      user: string,
      rawAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  EHDT_CancelRemainingAskOrder(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_CancelRemainingBidOrder(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_FullyCancelAsk(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_FullyCancelBid(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_FullyClaimAsk(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_FullyClaimBid(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_FullyMarketAsk(
    user: string,
    baseAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_FullyMarketBid(
    user: string,
    rawAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_LimitAsk(
    user: string,
    priceIndex: BigNumberish,
    baseAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_LimitBid(
    user: string,
    priceIndex: BigNumberish,
    rawAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_PartiallyCancelAsk(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_PartiallyCancelBid(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_PartiallyClaimAsk(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_PartiallyClaimBid(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_PartiallyMarketAsk(
    user: string,
    baseAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHDT_PartiallyMarketBid(
    user: string,
    rawAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_CancelRemainingAskOrder(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_CancelRemainingBidOrder(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_FullyCancelAsk(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_FullyCancelBid(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_FullyClaimAsk(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_FullyClaimBid(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_FullyMarketAsk(
    user: string,
    baseAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_FullyMarketBid(
    user: string,
    rawAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_LimitAsk(
    user: string,
    priceIndex: BigNumberish,
    baseAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_LimitBid(
    user: string,
    priceIndex: BigNumberish,
    rawAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_PartiallyCancelAsk(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_PartiallyCancelBid(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_PartiallyClaimAsk(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_PartiallyClaimBid(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_PartiallyMarketAsk(
    user: string,
    baseAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  EHET_PartiallyMarketBid(
    user: string,
    rawAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_CancelRemainingAskOrder(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_CancelRemainingBidOrder(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_FullyCancelAsk(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_FullyCancelBid(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_FullyClaimAsk(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_FullyClaimBid(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_FullyMarketAsk(
    user: string,
    baseAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_FullyMarketBid(
    user: string,
    rawAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_LimitAsk(
    user: string,
    priceIndex: BigNumberish,
    baseAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_LimitBid(
    user: string,
    priceIndex: BigNumberish,
    rawAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_PartiallyCancelAsk(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_PartiallyCancelBid(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_PartiallyClaimAsk(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_PartiallyClaimBid(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_PartiallyMarketAsk(
    user: string,
    baseAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHET_PartiallyMarketBid(
    user: string,
    rawAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_CancelRemainingAskOrder(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_CancelRemainingBidOrder(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_FullyCancelAsk(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_FullyCancelBid(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_FullyClaimAsk(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_FullyClaimBid(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_FullyMarketAsk(
    user: string,
    baseAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_FullyMarketBid(
    user: string,
    rawAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_LimitAsk(
    user: string,
    priceIndex: BigNumberish,
    baseAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_LimitBid(
    user: string,
    priceIndex: BigNumberish,
    rawAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_PartiallyCancelAsk(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_PartiallyCancelBid(
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_PartiallyClaimAsk(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_PartiallyClaimBid(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_PartiallyMarketAsk(
    user: string,
    baseAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  FHFT_PartiallyMarketBid(
    user: string,
    rawAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  cancelOrder(
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  claimOrder(
    isBid: boolean,
    priceIndex: BigNumberish,
    orderIndex: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  limitAskOrder(
    user: string,
    priceIndex: BigNumberish,
    baseAmount: BigNumberish,
    postOnly: boolean,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  limitBidOrder(
    user: string,
    priceIndex: BigNumberish,
    rawAmount: BigNumberish,
    postOnly: boolean,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  marketAskOrder(
    user: string,
    baseAmount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  marketBidOrder(
    user: string,
    rawAmount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    EHDT_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    EHDT_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    EHDT_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHDT_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    EHET_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    EHET_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    EHET_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    FHET_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    FHET_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHET_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    FHFT_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    FHFT_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    FHFT_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelOrder(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimOrder(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    limitAskOrder(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      postOnly: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    limitBidOrder(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      postOnly: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    marketAskOrder(
      user: string,
      baseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    marketBidOrder(
      user: string,
      rawAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    EHDT_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHDT_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    EHET_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHET_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    FHFT_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    cancelOrder(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    claimOrder(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    limitAskOrder(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      postOnly: boolean,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    limitBidOrder(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      postOnly: boolean,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    marketAskOrder(
      user: string,
      baseAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    marketBidOrder(
      user: string,
      rawAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    EHDT_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHDT_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EHET_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHET_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_CancelRemainingAskOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_CancelRemainingBidOrder(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_FullyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_FullyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_FullyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_FullyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_FullyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_FullyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_LimitAsk(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_LimitBid(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_PartiallyCancelAsk(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_PartiallyCancelBid(
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_PartiallyClaimAsk(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_PartiallyClaimBid(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_PartiallyMarketAsk(
      user: string,
      baseAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    FHFT_PartiallyMarketBid(
      user: string,
      rawAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    cancelOrder(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claimOrder(
      isBid: boolean,
      priceIndex: BigNumberish,
      orderIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    limitAskOrder(
      user: string,
      priceIndex: BigNumberish,
      baseAmount: BigNumberish,
      postOnly: boolean,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    limitBidOrder(
      user: string,
      priceIndex: BigNumberish,
      rawAmount: BigNumberish,
      postOnly: boolean,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    marketAskOrder(
      user: string,
      baseAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    marketBidOrder(
      user: string,
      rawAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
