/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MockPriceBook,
  MockPriceBookInterface,
} from "../../../contracts/mocks/MockPriceBook";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint16",
        name: "priceIndex",
        type: "uint16",
      },
    ],
    name: "indexToPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "maxPriceIndex",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "roundingUp",
        type: "bool",
      },
    ],
    name: "priceToIndex",
    outputs: [
      {
        internalType: "uint16",
        name: "priceIndex",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "priceUpperBound",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610347806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c8063523fdc71146100515780636a204d0c146100835780637242ec1d146100a4578063b9728219146100b4575b600080fd5b61006461005f366004610210565b6100c4565b6040805161ffff90931683526020830191909152015b60405180910390f35b610096610091366004610245565b61019e565b60405190815260200161007a565b60405161fff0815260200161007a565b690de0b6b3a76400000000610096565b600080806100da670de0b6b3a764000086610286565b1180156100e45750825b1561010d576100fb670de0b6b3a7640000856102b0565b6101069060016102c4565b9150610122565b61011f670de0b6b3a7640000856102b0565b91505b618ffc61ffff831611156101695760405162461bcd60e51b815260206004820152600960248201526809a82b0be929c888ab60bb1b60448201526064015b60405180910390fd5b81610180670de0b6b3a764000061ffff83166102dd565b9092506fffffffffffffffffffffffffffffffff1690509250929050565b6000618ffc61ffff831611156101e25760405162461bcd60e51b815260206004820152600960248201526809a82b0be929c888ab60bb1b6044820152606401610160565b6101f8670de0b6b3a764000061ffff84166102dd565b6fffffffffffffffffffffffffffffffff1692915050565b6000806040838503121561022357600080fd5b823591506020830135801515811461023a57600080fd5b809150509250929050565b60006020828403121561025757600080fd5b813561ffff8116811461026957600080fd5b9392505050565b634e487b7160e01b600052601260045260246000fd5b60008261029557610295610270565b500690565b634e487b7160e01b600052601160045260246000fd5b6000826102bf576102bf610270565b500490565b808201808211156102d7576102d761029a565b92915050565b6fffffffffffffffffffffffffffffffff8181168382160280821691908281146103095761030961029a565b50509291505056fea2646970667358221220069eeaa067c8c1612315a7d56c8e7b7c1798ef52a94552034052b5164ec331b764736f6c63430008110033";

type MockPriceBookConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockPriceBookConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockPriceBook__factory extends ContractFactory {
  constructor(...args: MockPriceBookConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<MockPriceBook> {
    return super.deploy(overrides || {}) as Promise<MockPriceBook>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MockPriceBook {
    return super.attach(address) as MockPriceBook;
  }
  override connect(signer: Signer): MockPriceBook__factory {
    return super.connect(signer) as MockPriceBook__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockPriceBookInterface {
    return new utils.Interface(_abi) as MockPriceBookInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockPriceBook {
    return new Contract(address, _abi, signerOrProvider) as MockPriceBook;
  }
}
